apiVersion: v1
kind: Service
metadata:
  name: scientist-name-generator-service
spec:
  selector:
    app: scientist-name-generator-service
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 8090
  type: NodePort




