apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.6
        ports:
        - containerPort: 16686 # Jaeger UI
        - containerPort: 6831   # UDP for Jaeger Agent
        - containerPort: 5775   # UDP for Jaeger Agent metrics
        - containerPort: 6832   # Zipkin HTTP for Jaeger Agent
        - containerPort: 5778   # gRPC for Jaeger Collector
        - containerPort: 14268  # HTTP for Jaeger Collector
        - containerPort: 9411   # Zipkin HTTP
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui
    port: 16686
    targetPort: 16686
  - name: jaeger-agent-udp
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: jaeger-agent-metrics-udp
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: jaeger-agent-zipkin-udp
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: jaeger-collector-grpc
    port: 5778
    targetPort: 5778
  - name: jaeger-collector-http
    port: 14268
    targetPort: 14268
  - name: jaeger-zipkin
    port: 9411
    targetPort: 9411
  type: NodePort
    


